<!DOCTYPE html>
<html>
<head>
    <title>My Site title:: List of Categories</title>
    <style>
        <?php include 'css/styles.css'; ?>
    </style>
    <script>
        <?php include 'js/myscript.js'; ?>
    </script>
</head>
<body onresize="onResize()" onpageshow="onResize()" >
<header id="header">
    <?php
    include 'actions/header.inc';
    ?>
</header>
<main id="main">
    <h2>This page is under construction yet... pls wait for the update.</h2>
</main>
</body>

</html>