
<h2> Your blog Database needs to be configured!</h2>
<h3> We will install your blog for you in few easy to follow steps.</h3>
<h3>Please provide your Data Base information in the form below</h3>
<form action="index.php" method="POST">
    DataBase name: <input type="text" name="dbname"><br>
    User name: <input type="text" name="user"><br>
    Password: <input type="password" name="password"><br>
    <input type="hidden" name="step" value = "1" >
     <input type="submit" value="Continue to step one &rarr; ">
</form>
