<div class="formFrame">
    <h3>Please enter e-mail and password.</h3>

    <!--Login form-->

    <form action="?profile" method="post">
        <span> E-mail:</span> <input type="text" name="email" size="50"><br><br>
        <span>Password:</span><input type="password" name="password" size="50"><br><br>
        <input type="hidden" name="login" value="true"><br>
        <input type="submit" value="L o g i n" class="submit">
    </form>
</div>